shiva
---
- hosts: all
  become: yes
  tasks:
    - name: install a webserver redhat/centos
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'RedHat'
    - name: start the service
      service:
         name: httpd
         state: started
      when: ansible_distribution == 'RedHat'
    - name: install a webserver on ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'
    - name: start the service
      service:
         name: apache2
         state: started
      when: ansible_distribution == 'Ubuntu'
