---
- hosts: all
  become: yes
  tasks:
    - name: ensure nginx is at the latest version
      apt: 
        name: nginx 
        state: latest
    - name: copy the content of the web site
      shell: echo "hi there, Ansible is Cool" > "/var/www/html/index.html"
    - name: start nginx
      service:
          name: nginx
          state: restarted
